---@meta
-- Lua API definitions generated by LuaDox 2.0.0dev0.
-- Fixture
-- This file is generated. Do not edit.

---A module whose documentation links to a manual page other than the landing page.
manual_pages = {}

---Runs the thing the guide describes.
---@return any
function manual_pages.run() end
