---@meta
-- Lua API definitions generated by LuaDox 2.0.0dev0.
-- Fixture
-- This file is generated. Do not edit.

---@class Doc
Doc = {}

---Reads a value.
---
---**Careful with this**
---The note body continues on a second line.
---
---And a second paragraph inside the note.
---**Warning**
---Data loss is possible.
---Text after both admonitions, back at the outer level.
---@return any
function Doc.read() end
