---@meta
-- Lua API definitions generated by LuaDox 2.0.0dev0.
-- Fixture
-- This file is generated. Do not edit.

---@class Actual
Actual = {}

---A class reachable under a second name.
---@class Aliased
Aliased = {}

---Returns an aliased thing.
---@return Aliased # The aliased class, referenced by its alias.
function Shell.make() end

---@class Shell
Shell = {}

---A field whose source symbol is requalified by the section's @scope.
---@type any
Shell.thing = nil
