---@meta
-- Lua API definitions generated by LuaDox 2.0.0dev0.
-- Fixture
-- This file is generated. Do not edit.

-- Namespace tables for members declared under them.
module_then_section = {}

---Base directory for generated files.
---@type string
module_then_section.base_path = nil

---How many entries to keep.
---@type integer
module_then_section.max_entries = nil

---Reloads the settings from disk.
---@return any
function reload() end
