---@meta
-- Lua API definitions generated by LuaDox 2.0.0dev0.
-- Fixture
-- This file is generated. Do not edit.

---A module with awkward comment shapes. Declarations inside `--[[ ]]` long comments
---are a recorded deviation and are left out here.
comments_edge = {}

---Four dashes below this line.
---still the same block?
---@type number
comments_edge.dashes = nil

---@type number
comments_edge.empty_first_line = nil

---Block one.
---@type number
comments_edge.one = nil

---Block two right after, no blank line.
---@type number
comments_edge.two = nil

---Tab-indented block.
---@type number
comments_edge.tabbed = nil

---Doc with a --[[ long ]] comment marker inline in text.
---@type number
comments_edge.inline_marker = nil

---Doc ending with a fence that never closes.
---```
---@type number
comments_edge.unclosed = nil
