---@meta
-- Lua API definitions generated by LuaDox 2.0.0dev0.
-- Fixture
-- This file is generated. Do not edit.

---@class Color
Color = {}

---@class Shape
Shape = {}

---Paints a shape.
---@param on boolean Whether to paint.
---@param count integer How many times.
---@param ratio number The ratio.
---@param precise number The precise ratio.
---@param color Color A documented class used as a type.
---@param thing Unknown A name that resolves to nothing.
---@param scoped engine::Color A C++ scoped name.
---@param label string|nil A union of two built-ins.
---@return nil
function Shape.paint(on, count, ratio, precise, color, thing, scoped, label) end

---A function whose parameter has no @tparam at all.
---@param a any
---@return any
function Shape.undocumented(a) end
