---@meta
-- Lua API definitions generated by LuaDox 2.0.0dev0.
-- Fixture
-- This file is generated. Do not edit.

---A class whose tags are written every way people write them.
---@class Tight
Tight = {}

---A cross reference at the start of a line is not a tag: Tight.spaced().
---Tight.unknown() starts this line.
---@type string|number|nil
Tight.union = nil

---Trailing spaces after a tag.
---@type string
Tight.trailing = nil

---Field meta.
---
---*read-only*
---@type string
Tight.meta_field = nil

---@param a string no space after the dashes
---@param b number a space
---@param c boolean only two dashes and no space
---@return string # first
---@return number # second
function Tight.spaced(a, b, c) end

---Unknown tags are reported and ignored.
---@return any
function Tight.unknown() end

---**Deprecated**
---use Tight.spaced
---
---really
---Deprecated twice.
---@return any
function Tight.old() end

---A @meta on a function is resolved, on a field carried through.
---@return any
function Tight.meta_fn() end
