//! The LuaLS renderer: one `---@meta` definition file the Lua language server can read.
//!
//! Implemented against `spec/luals.md`, which was written from the same pinned oracle,
//! rather than against `render/luals.py`. Reading the Python while porting is how a port
//! inherits a behaviour without noticing it is one.
//!
//! Two things about this renderer are easy to assume wrongly, and both are load-bearing:
//!
//!   * **It maps type names; the html renderer does not.** `@treturn void` reads `void`
//!     on an html page and `nil` here. A "format a type" helper shared between the two
//!     renderers is already wrong.
//!   * **It resolves a cross reference against the element being emitted**, not against
//!     the collection that element is in -- which is what the json renderer does. The
//!     Python's laziness makes the difference invisible until two renderers disagree
//!     about what a bare `@{Foo}` meant.

use std::collections::{BTreeSet, HashSet};

use crate::ir::{Content, Fragment, ItemId, Kind};
use crate::parse::Parser;
use crate::util;

/// LuaDox type names that have a different spelling in LuaLS. Everything else -- most
/// importantly a class name -- is passed through so cross references keep working.
const TYPE_MAP: [(&str, &str); 5] = [
    ("bool", "boolean"),
    ("int", "integer"),
    ("float", "number"),
    ("double", "number"),
    ("void", "nil"),
];

/// Type names the language server understands with no declaration.
const LUALS_BUILTIN_TYPES: [&str; 13] = [
    "any",
    "boolean",
    "string",
    "number",
    "integer",
    "function",
    "table",
    "thread",
    "userdata",
    "lightuserdata",
    "nil",
    "unknown",
    "self",
];

/// What a documented member with no `@type` is given. Permissive on purpose: it never
/// produces a false type error on correct code.
const DEFAULT_FIELD_TYPE: &str = "any";

/// The version string the header carries. It is the Python package's, not this crate's:
/// the file says which luadox generated it, and two implementations of one specification
/// generating different headers would be a difference in output.
const LUADOX_VERSION: &str = "2.0.0dev0";

struct Renderer<'a> {
    parser: &'a mut Parser,
    lines: Vec<String>,
    classnames: HashSet<String>,
    mixin_suffix: String,
    mixin_phrase: String,
}

pub fn render(parser: &mut Parser, toprefs: &[ItemId]) -> Result<String, String> {
    let classnames = toprefs
        .iter()
        .filter(|id| parser.item(**id).kind == Kind::Class)
        .map(|id| parser.item(*id).name.clone())
        .collect();
    let mixin_suffix = parser.config.get_or("luals", "mixin_suffix", "");
    let mixin_phrase = parser.config.get_or("luals", "mixin_doc_phrase", "");
    let globals = parse_globals(&parser.config.get_or("luals", "globals", ""))?;

    let mut r = Renderer {
        parser,
        lines: Vec::new(),
        classnames,
        mixin_suffix,
        mixin_phrase,
    };

    r.out("---@meta");
    r.out(format!(
        "-- Lua API definitions generated by LuaDox {LUADOX_VERSION}."
    ));
    let title = r
        .parser
        .config
        .get("project", "title")
        .or_else(|| r.parser.config.get("project", "name"))
        .map(str::to_string);
    if let Some(title) = title {
        r.out(format!("-- {title}"));
    }
    r.out("-- This file is generated. Do not edit.");
    r.out("");

    if !globals.is_empty() {
        // A configured global has no source location and resolves globally, so the parse
        // context is cleared to keep a stale file:line off any diagnostic it produces.
        r.parser.ctx.item = None;
        r.parser.ctx.file = None;
        r.parser.ctx.line = None;
        r.out("-- Globals injected into the script execution environment.");
        for (name, typ) in globals {
            let mapped = r.map_type(&[typ]);
            r.out(format!("---@type {mapped}"));
            r.out(format!("{name} = nil"));
        }
        r.out("");
    }

    for topref in toprefs {
        let item = r.parser.item(*topref);
        if item.empty && item.implicit {
            continue;
        }
        match item.kind {
            Kind::Class => r.emit_class(*topref),
            Kind::Module => r.emit_module(*topref),
            // A manual page is prose with no API surface.
            _ => {}
        }
    }

    r.insert_namespace_stubs();
    Ok(r.lines.join("\n").trim_end().to_string() + "\n")
}

/// `name[:type]` tokens, whitespace-separated and quotable across several indented lines.
fn parse_globals(value: &str) -> Result<Vec<(String, String)>, String> {
    let mut out = Vec::new();
    for line in value.lines() {
        for token in util::shlex_split(line) {
            let (name, typ) = match token.split_once(':') {
                Some((name, typ)) => (name.to_string(), typ.to_string()),
                None => (token.clone(), String::new()),
            };
            // A malformed name would be emitted as an assignment target and make the
            // whole definitions file syntactically invalid, so this fails rather than
            // dropping it silently.
            if !is_dotted_identifier(&name) {
                return Err(format!(
                    "invalid [luals] globals token \"{token}\": expected name[:type]"
                ));
            }
            out.push((
                name,
                if typ.is_empty() {
                    DEFAULT_FIELD_TYPE.to_string()
                } else {
                    typ
                },
            ));
        }
    }
    Ok(out)
}

fn is_identifier(name: &str) -> bool {
    let mut chars = name.chars();
    chars
        .next()
        .is_some_and(|c| c.is_ascii_alphabetic() || c == '_')
        && chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

fn is_dotted_identifier(name: &str) -> bool {
    !name.is_empty() && name.split('.').all(is_identifier)
}

impl Renderer<'_> {
    fn out(&mut self, line: impl Into<String>) {
        self.lines.push(line.into());
    }

    // -- blocks ----------------------------------------------------------------

    fn emit_class(&mut self, topref: ItemId) {
        self.parser.focus(topref);
        let lines = self.content_lines(topref);
        self.emit_doc(lines);
        let mut decl = format!("---@class {}", self.parser.item(topref).name);
        let parents = self.class_parents(topref);
        if !parents.is_empty() {
            decl += &format!(" : {}", parents.join(", "));
        }
        self.out(decl);
        self.out(format!("{} = {{}}", self.parser.item(topref).name));
        self.out("");
        self.emit_collections(topref);
    }

    fn emit_module(&mut self, topref: ItemId) {
        self.parser.focus(topref);
        // An implicit module stands in for a source file rather than for a real Lua
        // table, so its members are emitted as globals and its own doc comment is lost.
        if !self.parser.item(topref).implicit {
            let lines = self.content_lines(topref);
            self.emit_doc(lines);
            self.out(format!("{} = {{}}", self.parser.item(topref).name));
            self.out("");
        }
        self.emit_collections(topref);
    }

    fn emit_collections(&mut self, topref: ItemId) {
        for col in self.parser.item(topref).collections.clone() {
            self.parser.focus(col);
            if self.parser.item(col).kind == Kind::Table {
                self.emit_table(col);
            } else {
                self.emit_members(col);
            }
        }
    }

    fn emit_table(&mut self, col: ItemId) {
        self.parser.focus(col);
        // The leading sentence was popped into the heading during prerender, so the two
        // are recombined for the table's doc comment.
        let heading = self.parser.item(col).heading.clone();
        let mut lines = if heading.is_empty() {
            Vec::new()
        } else {
            vec![strip_links(&heading)]
        };
        lines.extend(self.content_lines(col));
        self.emit_doc(lines);
        // A table is modelled as a class so its name resolves in a type position and its
        // members can be accessed. A `@table` is not necessarily an integer enumeration,
        // so members default to the same permissive `any` as a class field.
        let name = self.parser.item(col).name.clone();
        self.out(format!("---@class {name}"));
        self.out(format!("{name} = {{}}"));
        self.out("");
        self.emit_members(col);
    }

    fn emit_members(&mut self, col: ItemId) {
        for id in self.parser.item(col).fields.clone() {
            self.emit_field(id);
        }
        for id in self.parser.item(col).functions.clone() {
            self.emit_function(id);
        }
    }

    fn emit_field(&mut self, id: ItemId) {
        self.parser.focus(id);
        let mut lines = self.content_lines(id);
        if let Some(meta) = self.parser.item(id).meta.clone().filter(|m| !m.is_empty()) {
            lines.push(format!("*{}*", strip_links(&meta)));
        }
        self.emit_doc(lines);
        let types = self.parser.item(id).types.clone();
        let typ = if types.is_empty() {
            DEFAULT_FIELD_TYPE.to_string()
        } else {
            self.map_type(&types)
        };
        self.out(format!("---@type {typ}"));
        let lhs = self.field_lhs(id);
        self.out(format!("{lhs} = nil"));
        self.out("");
    }

    fn emit_function(&mut self, id: ItemId) {
        self.parser.focus(id);
        let lines = self.content_lines(id);
        self.emit_doc(lines);

        let params = self.parser.item(id).params.clone();
        for param in &params {
            let mut line = format!("---@param {} {}", param.name, self.map_type(&param.types));
            let mut content = param.content.clone();
            self.parser.resolve_content(&mut content);
            let desc = self.inline(&content);
            if !desc.is_empty() {
                line += &format!(" {desc}");
            }
            self.out(line);
        }

        let returns = self.parser.item(id).returns.clone();
        if returns.is_empty() {
            // With no documented return, an empty body makes the language server infer
            // `nil` and reject `local x = obj:create()`, so fall back to the same
            // permissive `any` the fields use rather than claim nil.
            self.out(format!("---@return {DEFAULT_FIELD_TYPE}"));
        } else {
            for ret in &returns {
                let mut line = format!("---@return {}", self.map_type(&ret.types));
                let mut content = ret.content.clone();
                self.parser.resolve_content(&mut content);
                let desc = self.inline(&content);
                if !desc.is_empty() {
                    // ` # ` is the LuaLS marker between a return's type and its
                    // description. A parameter uses a plain space.
                    line += &format!(" # {desc}");
                }
                self.out(line);
            }
        }

        let names: Vec<String> = params.iter().map(|p| p.name.clone()).collect();
        // `symbol` is the real source-level callable -- `Class:method`, `Class.func` or a
        // bare global -- so it produces the correct definition in every case.
        let symbol = self.parser.item(id).symbol.clone();
        self.out(format!("function {symbol}({}) end", names.join(", ")));
        self.out("");
    }

    /// Fields scoped directly to an implicit module are globals and use the bare symbol;
    /// everywhere else the fully qualified name is the real access path.
    fn field_lhs(&self, id: ItemId) -> String {
        let item = self.parser.item(id);
        let scope_is_implicit_module = item.scope().is_some_and(|s| {
            let scope = self.parser.item(s);
            scope.kind == Kind::Module && scope.implicit
        });
        if scope_is_implicit_module {
            item.symbol.clone()
        } else {
            item.name.clone()
        }
    }

    // -- doc comments ----------------------------------------------------------

    /// The element's content, resolved against whatever is focused, as markdown lines.
    fn content_lines(&mut self, id: ItemId) -> Vec<String> {
        let mut content = std::mem::take(&mut self.parser.item_mut(id).content);
        self.parser.resolve_content(&mut content);
        let lines = self.content_to_lines(&content);
        self.parser.item_mut(id).content = content;
        lines
    }

    fn content_to_lines(&self, content: &Content) -> Vec<String> {
        let mut lines = Vec::new();
        for fragment in &content.0 {
            match fragment {
                Fragment::Markdown(md) => {
                    lines.extend(strip_links(&md.get()).split('\n').map(str::to_string));
                }
                Fragment::Admonition { title, content, .. } => {
                    let title = strip_links(title);
                    lines.push(format!("**{title}**"));
                    lines.extend(self.content_to_lines(content));
                }
                Fragment::SeeAlso(refs) => {
                    let names: Vec<String> = refs
                        .iter()
                        .map(|refid| match self.parser.item_by_id(refid) {
                            Some(found) => self.parser.item(found).name.clone(),
                            None => refid.clone(),
                        })
                        .collect();
                    if !names.is_empty() {
                        lines.push(format!("See also: {}", names.join(", ")));
                    }
                }
            }
        }
        lines
    }

    /// One line, for a `@param` or `@return` description.
    fn inline(&self, content: &Content) -> String {
        let text = self.content_to_lines(content).join(" ");
        text.split_whitespace().collect::<Vec<_>>().join(" ")
    }

    /// Emits markdown as a `---` comment, trimming the blank lines around it.
    fn emit_doc(&mut self, mut lines: Vec<String>) {
        while lines.first().is_some_and(|l| l.trim().is_empty()) {
            lines.remove(0);
        }
        while lines.last().is_some_and(|l| l.trim().is_empty()) {
            lines.pop();
        }
        for line in lines {
            // No wrapping, no escaping, no length limit: a content line goes through
            // byte for byte. A line already starting with `-` simply concatenates.
            if line.trim().is_empty() {
                self.out("---");
            } else {
                self.out(format!("---{line}"));
            }
        }
    }

    // -- types -----------------------------------------------------------------

    fn map_type(&mut self, types: &[String]) -> String {
        let mut mapped: Vec<String> = Vec::new();
        for entry in types {
            for part in entry.split('|') {
                let part = part.trim();
                if part.is_empty() {
                    continue;
                }
                // C++ scoped names leak in from bindings documentation. LuaLS reads
                // everything up to `::` as the type, so the parameter would silently be
                // typed as the enclosing class. Report it and emit it verbatim rather
                // than repairing it.
                if part.contains("::") {
                    self.report_type(format!(
                        "type name \"{part}\" uses C++ scope syntax; use \".\""
                    ));
                    mapped.push(part.to_string());
                    continue;
                }
                if let Some((_, to)) = TYPE_MAP.iter().find(|(from, _)| *from == part) {
                    mapped.push((*to).to_string());
                    continue;
                }
                // Resolution is relative to what is focused, so an unqualified name maps
                // the way a cross reference would. A field or function of the same name
                // must not hijack a type position.
                let found = self.parser.resolve_ref(part);
                if let Some(found) = found {
                    if matches!(self.parser.item(found).kind, Kind::Class | Kind::Table) {
                        mapped.push(self.parser.item(found).name.clone());
                        continue;
                    }
                }
                if !LUALS_BUILTIN_TYPES.contains(&part) && is_plain_type_name(part) {
                    self.report_type(format!(
                        "type name \"{part}\" does not resolve to a documented class or table"
                    ));
                }
                mapped.push(part.to_string());
            }
        }
        if mapped.is_empty() {
            DEFAULT_FIELD_TYPE.to_string()
        } else {
            mapped.join("|")
        }
    }

    fn report_type(&mut self, message: String) {
        let (file, line) = (self.parser.ctx.file.clone(), self.parser.ctx.line);
        self.parser
            .diagnostics
            .add(crate::diag::Category::Types, message, file.as_deref(), line);
    }

    // -- parents ---------------------------------------------------------------

    fn class_parents(&mut self, topref: ItemId) -> Vec<String> {
        let mut parents: Vec<String> = Vec::new();
        let own = self.parser.item(topref).name.clone();
        let add = |parents: &mut Vec<String>, name: String| {
            if !name.is_empty() && name != own && !parents.contains(&name) {
                parents.push(name);
            }
        };

        // Every `@inherits` entry, resolved or not: a parent that names no documented
        // class is emitted anyway, and the prerender stage reports it.
        for name in self.parser.item(topref).flags.inherits.clone() {
            add(&mut parents, name);
        }
        // A convention for APIs where `Foo` has a companion `FooMetadata` whose members
        // are accessed as `Foo.Member`.
        if !self.mixin_suffix.is_empty() {
            let candidate = format!("{own}{}", self.mixin_suffix);
            if self.classnames.contains(&candidate) {
                add(&mut parents, candidate);
            }
        }
        for name in self.doc_mixins(topref) {
            if self.classnames.contains(&name) {
                add(&mut parents, name);
            }
        }
        parents
    }

    /// Parents named in prose rather than in a tag: "Inherits properties from `@{A}`".
    ///
    /// The content is read *after* link resolution, so the phrase must match the prose as
    /// written and the references must be ones that resolved.
    fn doc_mixins(&self, topref: ItemId) -> Vec<String> {
        if self.mixin_phrase.is_empty() {
            return Vec::new();
        }
        let mut names = Vec::new();
        for fragment in &self.parser.item(topref).content.0 {
            let Fragment::Markdown(md) = fragment else {
                continue;
            };
            for line in md.get().split('\n') {
                if !line.contains(&self.mixin_phrase) {
                    continue;
                }
                for refid in luadox_ids(line) {
                    if let Some(found) = self.parser.item_by_id(&refid) {
                        if self.parser.item(found).kind == Kind::Class {
                            names.push(self.parser.item(found).name.clone());
                        }
                    }
                }
            }
        }
        names
    }

    // -- namespace stubs -------------------------------------------------------

    /// Declares a table for any root that the output uses but never declares, which the
    /// language server would otherwise flag as an undefined global.
    fn insert_namespace_stubs(&mut self) {
        let mut declared: HashSet<String> = HashSet::new();
        let mut used: BTreeSet<String> = BTreeSet::new();
        for line in &self.lines {
            if let Some(name) = declares(line) {
                declared.insert(name);
            }
            if let Some(name) = uses_root(line) {
                used.insert(name);
            }
        }
        let stubs: Vec<String> = used.into_iter().filter(|n| !declared.contains(n)).collect();
        if stubs.is_empty() {
            return;
        }
        let mut insert = vec!["-- Namespace tables for members declared under them.".to_string()];
        insert.extend(stubs.into_iter().map(|name| format!("{name} = {{}}")));
        insert.push(String::new());
        // Right after the header block, which is the first empty line.
        let at = self
            .lines
            .iter()
            .position(|l| l.is_empty())
            .map(|i| i + 1)
            .unwrap_or(self.lines.len());
        self.lines.splice(at..at, insert);
    }
}

/// `<name> = ` or `function <name>(` at the start of a line.
fn declares(line: &str) -> Option<String> {
    if let Some(rest) = line.strip_prefix("function ") {
        let name = leading_identifier(rest)?;
        if rest.get(name.len()..)?.starts_with('(') {
            return Some(name);
        }
        return None;
    }
    let name = leading_identifier(line)?;
    line.get(name.len()..)?.starts_with(" = ").then_some(name)
}

/// `<name>.` or `<name>:` at the start of a line, optionally after `function `.
fn uses_root(line: &str) -> Option<String> {
    let rest = line.strip_prefix("function ").unwrap_or(line);
    let name = leading_identifier(rest)?;
    let next = rest.get(name.len()..)?.chars().next()?;
    (next == '.' || next == ':').then_some(name)
}

fn leading_identifier(s: &str) -> Option<String> {
    let mut chars = s.char_indices();
    let (_, first) = chars.next()?;
    if !(first.is_ascii_alphabetic() || first == '_') {
        return None;
    }
    let end = s
        .char_indices()
        .find(|(_, c)| !(c.is_ascii_alphanumeric() || *c == '_'))
        .map(|(i, _)| i)
        .unwrap_or(s.len());
    Some(s.get(..end)?.to_string())
}

/// `[text](luadox:<id>)` -> `text`. Only the links the prerender stage generated; an
/// ordinary markdown link, emphasis, fence, heading or raw html passes through, because a
/// LuaLS doc comment is markdown and the language server renders it as such.
fn strip_links(md: &str) -> String {
    let chars: Vec<char> = md.chars().collect();
    let mut out = String::with_capacity(md.len());
    let mut i = 0usize;
    while let Some(&c) = chars.get(i) {
        if c != '[' {
            out.push(c);
            i += 1;
            continue;
        }
        let mut j = i + 1;
        let mut text = String::new();
        while let Some(&c) = chars.get(j) {
            if c == ']' {
                break;
            }
            text.push(c);
            j += 1;
        }
        // `\[([^\]]*)\]\(luadox:[^)]*\)`
        let opens = chars.get(j) == Some(&']') && chars.get(j + 1) == Some(&'(');
        if !opens || !starts_with_at(&chars, j + 2, "luadox:") {
            out.push(c);
            i += 1;
            continue;
        }
        let mut k = j + 2;
        while let Some(&c) = chars.get(k) {
            if c == ')' {
                break;
            }
            k += 1;
        }
        if chars.get(k) != Some(&')') {
            out.push(c);
            i += 1;
            continue;
        }
        out.push_str(&text);
        i = k + 1;
    }
    out
}

fn starts_with_at(chars: &[char], at: usize, needle: &str) -> bool {
    needle
        .chars()
        .enumerate()
        .all(|(n, c)| chars.get(at + n) == Some(&c))
}

/// Every `luadox:<hex>` id mentioned on a line.
fn luadox_ids(line: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut rest = line;
    while let Some(at) = rest.find("luadox:") {
        let tail = rest.get(at + "luadox:".len()..).unwrap_or("");
        let end = tail
            .char_indices()
            .find(|(_, c)| !c.is_ascii_hexdigit())
            .map(|(i, _)| i)
            .unwrap_or(tail.len());
        if end > 0 {
            if let Some(id) = tail.get(..end) {
                out.push(id.to_string());
            }
        }
        rest = tail.get(end..).unwrap_or("");
    }
    out
}

/// `[A-Za-z_][\w.]*` -- what silences the report for a table-literal or function type
/// like `string[]` or `fun(x): number`, which are legal LuaLS.
fn is_plain_type_name(part: &str) -> bool {
    let mut chars = part.chars();
    chars
        .next()
        .is_some_and(|c| c.is_ascii_alphabetic() || c == '_')
        && chars.all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '.')
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn strip_links_removes_only_luadox_links() {
        assert_eq!(
            strip_links("see [Link.target](luadox:abc123)"),
            "see Link.target"
        );
        assert_eq!(
            strip_links("see [a renamed target](luadox:abc123) now"),
            "see a renamed target now"
        );
        assert_eq!(
            strip_links("an [ordinary](https://example.com) link"),
            "an [ordinary](https://example.com) link"
        );
        assert_eq!(strip_links("`[not a link]`"), "`[not a link]`");
    }

    #[test]
    fn the_stub_scan_reads_declarations_and_uses() {
        assert_eq!(declares("answer = nil"), Some("answer".into()));
        assert_eq!(declares("function ping() end"), Some("ping".into()));
        assert_eq!(declares("log.level = nil"), None);
        assert_eq!(uses_root("log.level = nil"), Some("log".into()));
        assert_eq!(
            uses_root("function Widget:move(x, y) end"),
            Some("Widget".into())
        );
        assert_eq!(uses_root("answer = nil"), None);
    }

    #[test]
    fn a_globals_token_needs_a_dotted_identifier() {
        assert_eq!(
            parse_globals("app:Application env"),
            Ok(vec![
                ("app".into(), "Application".into()),
                ("env".into(), "any".into())
            ])
        );
        assert!(parse_globals("9bad:X").is_err());
        assert_eq!(
            parse_globals("a.b.c").ok(),
            Some(vec![("a.b.c".into(), "any".into())])
        );
    }

    #[test]
    fn luadox_ids_finds_every_id_on_a_line() {
        assert_eq!(
            luadox_ids("from [A](luadox:aa11) and [B](luadox:bb22)."),
            vec!["aa11".to_string(), "bb22".to_string()]
        );
    }
}
