---@meta
-- Lua API definitions generated by LuaDox 2.0.0dev0.
-- Fixture
-- This file is generated. Do not edit.

---Focus scope kinds
---@class FocusScope
FocusScope = {}

---Focus is trapped inside the scope.
---@type any
FocusScope.Trap = nil

---@type any
FocusScope.Undocumented = nil

---A hexadecimal value.
---@type any
FocusScope.Hex = nil

---A value that is not an integer literal.
---@type any
FocusScope.Text = nil
