---@meta
-- Lua API definitions generated by LuaDox 2.0.0dev0.
-- Fixture
-- This file is generated. Do not edit.

---Every assignment shape the two implementations agree on. The shapes they disagree
---on by design -- a value spanning lines, `--` inside a string, a comparison, a tab
---before the `=` -- are in harness/improvements.toml, not here.
fields_edge = {}

---Bracket string key.
---@type number
fields_edge.key = nil

---Bracket single-quoted key.
---@type number
fields_edge.single = nil

---Bracket integer key.
---@type number
fields_edge.1 = nil

---Two targets, two values.
---@type number
fields_edge.b = nil

---Function value has no literal.
---@type any
fields_edge.f = nil

---Assigned from another field.
---@type function
fields_edge.g = nil

---A nested function in a table constructor.
---@type any
fields_edge.k = nil

---Semicolon separators.
---@type any
fields_edge.m = nil

---A field named like a keyword.
---@type number
fields_edge.end = nil

---Varargs.
---@param ... any
---@return any
function fields_edge.h(...) end

---Colon method with an unknown tag variant.
---@param a number first
---@param b any
---@return any
function fields_edge:i(a, b) end

---A local function.
---@return any
function j() end
