---@meta
-- Lua API definitions generated by LuaDox 2.0.0dev0.
-- Fixture
-- This file is generated. Do not edit.

---Markdown shapes inside documentation. An indented code block is the recorded
---CODE_INDENT deviation and is left out here.
markdown_edge = {}

---A fenced block that contains what looks like a tag.
---
---```lua
----- @tparam string x not a tag
---local y = x
---```
---@param x string the real one
---@return any
function markdown_edge.fenced(x) end

---Lists.
---
---* one
---* two
---  * nested
---
---1. first
---2. second
---
---- dash
---+ plus
---@return any
function markdown_edge.lists() end

---Inline shapes: *em*, _em_, **strong**, `code`, ~~strike~~, <b>raw</b>, &amp; &lt; &, <, >, "quotes", 'single', unicode: ⛔ é ü 漢.
---@return any
function markdown_edge.inline() end

---Links: [text](http://x.y), <http://auto.link>, ![img](img/a.png), [ref][r], labelled, `markdown_edge.lists`, nowhere, `nowhere.at.all`, markdown_edge.lists()().
---
---[r]: http://reference.link
---@return any
function markdown_edge.links() end

---Headings inside a doc.
---
---# H1
---## H2
---### H3
---
---Setext
---======
---@return any
function markdown_edge.headings() end

---A table with inline markdown and a pipe in code.
---
---| a | b |
---|---|---|
---| `x \| y` | **z** |
---| markdown_edge.lists() | |
---@return any
function markdown_edge.table() end

---Blockquote and rule.
---
---> quoted
---> lines
---
------
---
---after the rule
---@return any
function markdown_edge.quote() end

---Admonitions.
---**a note with `code`**
---**a warning**
---and its continuation
---See also: markdown_edge.lists
---##### Usage
---
---```lua
---```
---
---local m = require("markdown_edge")
---m.lists()
---@return any
function markdown_edge.admonitions() end

---Example from a file that does not exist.
---##### Example
---
---```missing_snippet.lua
---```
---@return any
function markdown_edge.example() end

---Code tag.
---```lua
---```
---
---local a = 1
---@return any
function markdown_edge.code() end

---Two paragraphs with a hard break at the end of the first
---continue here.
---
---Second paragraph.
---@return any
function markdown_edge.paragraphs() end
