---@meta
-- Lua API definitions generated by LuaDox 2.0.0dev0.
-- Fixture
-- This file is generated. Do not edit.

---@class Config
Config = {}

---Enables logging.
---@type any
Config.verbose = nil

---**Deprecated**
---Use verbose instead.
---Enables tracing.
---@type any
Config.trace = nil

---The retry count.
---@type any
Config.retries = nil

---Reloads the configuration.
---@param force boolean Reload even when unchanged.
---@return any
function Config.reload(force) end
