---@meta
-- Lua API definitions generated by LuaDox 2.0.0dev0.
-- Fixture
-- This file is generated. Do not edit.

-- Namespace tables for members declared under them.
Widget = {}

---Base.
---@class naming_edge.Base
naming_edge.Base = {}

---Fullnames.
---@class naming_edge.Full
naming_edge.Full = {}

---Member of Full.
---@type number
naming_edge.Full.member = nil

---Static under a class.
---@type number
naming_edge.Widget.count = nil

---A duplicate.
---@return any
function naming_edge.refs() end

---Mixin.
---@class naming_edge.Mixin
naming_edge.Mixin = {}

---Ordering.
---@return any
function naming_edge.z_first() end

---Renamed.
---@return any
function Widget.shown() end

---Displayed differently.
---@return any
function naming_edge.Widget:hide() end

---Scoped to the root.
---@return any
function helper() end

---Scoped elsewhere.
---@return any
function naming_edge.Base.moved() end

---Alias.
---@return any
function naming_edge.aliased() end

---References through the alias: ne.aliased, naming_edge.alt.aliased.
---@return any
function naming_edge.refs() end

---Ordered after a missing anchor.
---@return any
function naming_edge.a_last() end

---Also in the section, a field.
---@type number
naming_edge.sec_field = nil

---Within a section on another page.
---@return any
function naming_edge.Widget.util() end

---In the section.
---@return any
function naming_edge.sec_fn() end

---An enum
---@class naming_edge.Color
naming_edge.Color = {}

---Red.
---@type any
naming_edge.Color.RED = nil

---Green.
---@type any
naming_edge.Color.GREEN = nil

---Not an integer.
---@type any
naming_edge.Color.BLUE = nil

---@type any
naming_edge.Color.UNDOCUMENTED = nil

---A nested table
---@class naming_edge.outer
naming_edge.outer = {}

---After the inner table closed.
---@type number
naming_edge.outer.shallow = nil

---Inner table
---@class naming_edge.outer.inner
naming_edge.outer.inner = {}

---Deep field.
---@type number
naming_edge.outer.inner.deep = nil

---A class inside the module.
---@class naming_edge.Widget : naming_edge.Base, naming_edge.Mixin
naming_edge.Widget = {}

---Naming and scoping modifiers, all in one module, with a manual page that refers to them.
naming_edge = {}
