---@meta
-- Lua API definitions generated by LuaDox 2.0.0dev0.
-- Fixture
-- This file is generated. Do not edit.

---@class Other
Other = {}

---Declared third, pulled to the front.
---@type any
Other.first = nil

---Declared second, no order: ends up between the two.
---@type any
Other.middle = nil

---Declared first, pushed last.
---@type any
Other.last = nil

---@class Twin
Twin = {}

---The first field.
---@type any
Twin.duplicate = nil

---The second field under the same name, which does not replace the first.
---@type any
Twin.duplicate = nil

---Only on this one.
---@type any
Twin.second = nil

---Lives in the shared-named section.
---@type any
Twin.inShared = nil
