---@meta
-- Lua API definitions generated by LuaDox 2.0.0dev0.
-- Fixture
-- This file is generated. Do not edit.

---Graphics helpers.
gfx = {}

---The current backend name.
---@type string
gfx.backend = nil

---Draws a rectangle.
---@param w number Width.
---@return any
function gfx.draw(w) end
