---@meta
-- Lua API definitions generated by LuaDox 2.0.0dev0.
-- Fixture
-- This file is generated. Do not edit.

---A module documented with pipe tables.
markdown_table = {}

---Serves one request.
---
---| Parameter | Required | Description                     |
---|-----------|----------|---------------------------------|
---| action    | yes      | Must be set to `config`         |
---| verbose   | no       | Log every step                  |
---
---Alignment markers are part of the syntax too:
---
---| Left | Center | Right |
---|:-----|:------:|------:|
---| a    | b      | c     |
---@param params tab the request parameters
---@return any
function markdown_table.serve(params) end
