---@meta
-- Lua API definitions generated by LuaDox 2.0.0dev0.
-- Fixture
-- This file is generated. Do not edit.

-- Globals injected into the script execution environment.
---@type Application
app = nil
---@type any
env = nil

---The application object type.
---@class Application
Application = {}

---A widget.
---
---Inherits properties from WidgetMetadata and Application.
---@class Widget : WidgetMetadata, Application
Widget = {}

---Metadata for Widget.
---@class WidgetMetadata
WidgetMetadata = {}
