---@meta
-- Lua API definitions generated by LuaDox 2.0.0dev0.
-- Fixture
-- This file is generated. Do not edit.

---@class Base
Base = {}

---A class with several parents, one of which does not exist.
---@class Derived : Middle, Mixin, Missing
Derived = {}

---@class Middle : Base
Middle = {}

---@class Mixin
Mixin = {}
