---@meta
-- Lua API definitions generated by LuaDox 2.0.0dev0.
-- Fixture
-- This file is generated. Do not edit.

---A class the manual page links to.
---@class Doc
Doc = {}

---Reads a value.
---@return any
function Doc.read() end
