---@meta
-- Lua API definitions generated by LuaDox 2.0.0dev0.
-- Fixture
-- This file is generated. Do not edit.

---A module that assigns its own table right after the block declaring it, which is
---not a documented field of itself.
rtk_like = {}

---A real field of the module.
---@type integer
rtk_like.count = nil

---A table under the module, whose page is the module's
---@class rtk_like.themes
rtk_like.themes = {}

---The default theme's button colour.
---@type string
rtk_like.themes.button = nil
