---@meta
-- Lua API definitions generated by LuaDox 2.0.0dev0.
-- Fixture
-- This file is generated. Do not edit.

---A palette.
---@class Palette
Palette = {}

---Named colour slots
---@class Colors
Colors = {}

---The primary colour.
---@type any
Colors.Primary = nil

---The secondary colour, back at the outer level.
---@type any
Colors.Secondary = nil

---A nested group of accents
---@class Accents
Accents = {}

---The warm accent.
---@type any
Accents.Warm = nil
