---@meta
-- Lua API definitions generated by LuaDox 2.0.0dev0.
-- Fixture
-- This file is generated. Do not edit.

---@class Link
Link = {}

---The target field, declared after the function that references it.
---@type any
Link.target = nil

---Refers forward to Link.target, to a renamed target, and to
---`Link.target` in backticks.
---
---Unresolvable: NoSuchThing, with text, and `NoSuchAlso`.
---See also: Link.target
---@return Link # The same object.
function Link.get() end
