---@meta
-- Lua API definitions generated by LuaDox 2.0.0dev0.
-- Fixture
-- This file is generated. Do not edit.

---A widget on the screen.
---
---The second paragraph is body text, not synopsis text.
---@class Widget
Widget = {}

---The label shown on the widget.
---@type string
Widget.label = nil

---Moves the widget. The rest of this line is body, not synopsis.
---
---A second paragraph of the method body.
---@param x number Horizontal position.
---@param y number Vertical position.
---@return boolean # Whether the move happened.
---@return string # A diagnostic message.
function Widget:move(x, y) end

---A function with no documented return at all.
---@return any
function Widget.reset() end
