---@meta
-- Lua API definitions generated by LuaDox 2.0.0dev0.
-- Fixture
-- This file is generated. Do not edit.

---A chord, analysed from notes.
---@class Chord
Chord = {}

---The root note, assigned alongside a local in one statement.
---@type string
Chord.root = nil

---Two locals in one statement; the one before the `=` is documented.
---@type integer
Chord.second = nil

---Sorts notes and finds the root.
---@param notes tab the notes to analyse
---@return tab # the notes in chord order
---@return string # the root note
function Chord.analyze(notes) end
