---@meta
-- Lua API definitions generated by LuaDox 2.0.0dev0.
-- Fixture
-- This file is generated. Do not edit.

-- Namespace tables for members declared under them.
log = {}

---The current log level.
---@type integer
log.level = nil

---A bare global field.
---@type any
answer = nil

---Writes a log line.
---@param msg string The message.
---@return any
function log.write(msg) end

---A bare global function.
---@return any
function ping() end
