---@meta
-- Lua API definitions generated by LuaDox 2.0.0dev0.
-- Fixture
-- This file is generated. Do not edit.

---@class Ordered
Ordered = {}

---Declared second, ordered first by default.
---
---*read-only*
---@type any
Ordered.alpha = nil

---Declared in Extras, rendered in Members.
---@type any
Ordered.gamma = nil

---Declared first, ordered last.
---@type any
Ordered.beta = nil

---Stays in Extras.
---@type any
Ordered.delta = nil
