---@meta
-- Lua API definitions generated by LuaDox 2.0.0dev0.
-- Fixture
-- This file is generated. Do not edit.

---@class Ordered
Ordered = {}

---Declared second, ordered first by default.
---
---*read-only*
---@type any
Ordered.alpha = nil

---Declared in Extras, rendered in Members.
---@type any
Ordered.gamma = nil

---Declared first, ordered last.
---@type any
Ordered.beta = nil

---Stays in Extras.
---@type any
Ordered.delta = nil

---The anchor.
---@type any
Ordered.middle = nil

---Placed before the anchor even though it is declared after it.
---@type any
Ordered.ahead = nil

---Placed after the anchor.
---@type any
Ordered.behind = nil

---Anchored on a name nothing declares, which is reported rather than ignored.
---@type any
Ordered.stray = nil

---A field with no line of code under it.
---@type any
Ordered.injected = nil
