---@meta
-- Lua API definitions generated by LuaDox 2.0.0dev0.
-- Fixture
-- This file is generated. Do not edit.

---**Deprecated**
---Use Modern instead.
---A legacy class.
---@class Legacy
Legacy = {}

---**Deprecated**
---An old field, deprecated with no explanation.
---@type any
Legacy.old = nil

---**Deprecated**
---Call Modern instead.
---An old method.
---@return any
function Legacy:run() end

---The replacement class.
---@class Modern
Modern = {}
